# Jekyll configuration
title: "SuelenGC Site - Posts e vídeos techs, em português, diretos e sem firúlas você só encontra aqui!"
url: 'http://suelengc.github.io'
author: Suelen GC
twitter: 'suelengc'
github: 'suelengc'
email: 'suelengcarvalho@gmail'
description: 'Posts and tutorials about Java, Android, iOS, Hibernate, Spring, Web Development and others development stuffs SuelenGC'

category_title_prefix: ''
category_dir: /

# Basic configuration
permalink: /:year/:title/
destination: ./_publish
tag_dir: tag

# Use Pygments to highlight code blocks
baseurl: '/'
highlighter: pygments
paginate: 10
exclude: ['/node_modules', '/.gitignore', './config.ru', './Gemfile', './Gemfile.lock', './CNAME', '/gulpfile.js', '/package.json', '/README.md', '/src']

# Google Analytics configuration
analytics : 
  provider : google
  google : 
    tracking_id : 'UA-29893194-2'

# Publish posts with future date.
future: false

# Compile posts in the _drafts directory.
show_drafts: false

gems: ['jekyll-paginate']
